Pop Up windpws
Arturgouveia1970/Personal-portofolio pull request #18
Opened 2022-04-12 16:51 UTC by Arturgouveia1970

we will implement in this PR the popup windows for both the mobile and desktop versions.
so far I have created and styled, both versions.

2022-04-14 18:37 UTC, OLIPLICHE requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
Linter result is green ✔️
 Commit messages are meaningful✔️
 The pull request have a descriptive title telling you what changes are inside ✔️
 The pull request have a short summary describing introduced changes in more detail ✔️
 node_modules folder is in the .gitignore ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-14 18:37 UTC, OLIPLICHE commented on index.html
> +      <section class="projects" id="mobile-proj"></section>
- [ ] Please the `projects section` is created dynamically with the information from the projects array. Remember the [Project requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/8_popup.md): All of the HTML in that section is created when the page loads.
Therefore, What you need to do is:
- Kindly change the existing code; the already created HTML code for the `projects section` list should be removed, and instead it should be added via JavaScript

2022-04-14 18:37 UTC, OLIPLICHE commented on index.html
> +    </section>
- [ ] Please Modal popup data is populated with the data from the projects array. We don't need to see the popup code inside HTML.
  Kindly remember your [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/8_popup.md): In order to associate each project with the popup window details, you must use a JavaScript array to store all of the information for all projects...

- [ ] Kindly make sure the popup is responsive, it fits mobile and desktop sizes properly

2022-04-14 18:37 UTC, OLIPLICHE commented on mobile-menu.js
> +
- [ ] Please remove (delete) commented code to make your code Dry, clean, and more professional

2022-04-15 14:59 UTC, brytebee approved these changes
Hi Team👋,

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/3o6fIUZTTDl0IDjbZS/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-15 15:08 UTC, merged