Portofolio mobile skeleton
Arturgouveia1970/Personal-portofolio pull request #3
Opened 2022-03-16 20:36 UTC by Arturgouveia1970

final linters errors

2022-03-16 21:12 UTC, aimemalaika requested changes
Hi @Arturgouveia1970 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## Highlights
- Linters passed ✅ 
- Well described readme ✅ 
- Meaningful commit message ✅ 

## Required Changes ♻️

- [ ] Please apply the changes listed below.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-17 00:30 UTC, Arturgouveia1970 commented
Hello Aime, Would you be so kind as to giving me more precise instructions on the last 3 points. KindlyArturEnviado do meu telemóvel Huawei.-------- Mensagem original --------De: Aime Malaika ***@***.***>Data: quarta-feira, 16 de março de 2022, 22:13Para: Arturgouveia1970/Personal-portofolio ***@***.***>Cc: Arturgouveia1970 ***@***.***>, Mention ***@***.***>Assunto: Re: [Arturgouveia1970/Personal-portofolio] Portofolio mobile skeleton (PR #3)

@aimemalaika requested changes on this pull request.



Hi @Arturgouveia1970 ,

Good job so far!

There are some issues that you still need to work on to go to the next project but you are almost there!



Highlights

Linters passed ✅Well described readme ✅Meaningful commit message ✅

Required Changes ♻️

 Please apply the changes listed below.

Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.



As described in the Code reviews limits policy you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this form.



In index.html:

> @@ -0,0 +1,34 @@

+<!DOCTYPE html>

+<html lang="en">

+<head>

+    <meta charset="UTF-8">

+    <meta http-equiv="X-UA-Compatible" content="IE=edge">

+    <meta name="viewport" content="width=device-width, initial-scale=1.0">

+    <link rel="stylesheet" href="styles.css">

+    <title>Portofolio</title>

+</head>

+<body>

+  <header>

+    <div class="logo">Artur Gouveia</div>



 Kindly use the a tag for the website logo







In index.html:

> +    <ul>

+      <li><a href="#Portofolio">Portofolio</a></li>

+      <li><a href="#About">About</a></li>

+      <li><a href="#Contact">Contact</a></li> 

+    </ul>



 The hamburger button should be on the right and in a nav tag







In index.html:

> +  <section class="headline">

+    <div class="text">

+        <h1>Hey there. <br>I am Artur</h1>

+        <h4>I am a software Developer</h4>

+        <p>I can help you build a product , feature or website Look<br>

+             through some of my work and experience! If you like what<br> 

+             you see and have a project you need coded,<br> 

+             don’t hestiate to contact me.

+        </p>

+    </div>

+

+  </section>



 Kindly use the appropriate background image for the section, check the Figma design for more description.







In styles.css:

> +.text {

+  padding-left: 125px;

+}



 Kindly reduce the padding to match the text alignment to look like the Figma design. Kindly use flexbox to align the contents.



—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-03-17 01:19 UTC, aimemalaika commented
hello @Arturgouveia1970

2022-03-17 18:08 UTC, Kingstalux commented on index.html
> +    </ul>
resolved 👍

2022-03-17 18:10 UTC, Kingstalux commented on index.html
> +  </section>
resolved 👍

2022-03-17 18:15 UTC, Kingstalux approved these changes
Hi @Arturgouveia1970,
# Status: Approved ✔️ ✔️ ✔️ 
 
![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966](https://user-images.githubusercontent.com/85113567/158868598-bddb8203-fe77-4d65-b04c-0f4194ca79b6.gif)


Good job implementing the required changes 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
- [ ] (OPTIONAL) Kindly reduce the gap between the nav bar and the heading as your is too large 👍 
- Your design:
![Annotation 2022-03-17 191113](https://user-images.githubusercontent.com/85113567/158868825-ccc7163d-e6eb-4e28-ad2a-caaee7c152a0.jpg)
- Figma design:


![Annotation 2022-03-17 191152](https://user-images.githubusercontent.com/85113567/158868874-f08bb642-9d34-4e97-8be4-ecfa7ef00c3a.jpg)
- [ ] (OPTIONAL) It would be great if you could use the same icons as used in the template design. Right now your LinkedIn icon is different 
- Your icons:
![Annotation 2022-03-17 191210](https://user-images.githubusercontent.com/85113567/158869052-17ef9eb7-bcb6-4d0f-981b-e3144ce2db1d.jpg)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-17 20:27 UTC, merged

2022-03-19 00:24 UTC, Arturgouveia1970 commented
Hi guys,
while trying to make a commit got this message: error: failed to push some
refs to 'github.com:Arturgouveia1970/Personal-portofolio.git'.
I am desperate as I have my first weekly deadline.
please help
Artur

On Thu, 17 Mar 2022 at 19:15, Ngu Kingsely Junior Cho <
***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> Hi @Arturgouveia1970 <https://github.com/Arturgouveia1970>,
> Status: Approved ✔️ ✔️ ✔️
>
> [image:
> 68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966]
> <https://user-images.githubusercontent.com/85113567/158868598-bddb8203-fe77-4d65-b04c-0f4194ca79b6.gif>
>
> Good job implementing the required changes 👍 Your project is complete!
> There is nothing else to say other than... it's time to merge it [image:
> :shipit:]
> Congratulations! 🎉
>
>    - (OPTIONAL) Kindly reduce the gap between the nav bar and the heading
>    as your is too large 👍
>    - Your design:
>    [image: Annotation 2022-03-17 191113]
>    <https://user-images.githubusercontent.com/85113567/158868825-ccc7163d-e6eb-4e28-ad2a-caaee7c152a0.jpg>
>    - Figma design:
>
> [image: Annotation 2022-03-17 191152]
> <https://user-images.githubusercontent.com/85113567/158868874-f08bb642-9d34-4e97-8be4-ecfa7ef00c3a.jpg>
>
>    - (OPTIONAL) It would be great if you could use the same icons as used
>    in the template design. Right now your LinkedIn icon is different
>    - Your icons:
>    [image: Annotation 2022-03-17 191210]
>    <https://user-images.githubusercontent.com/85113567/158869052-17ef9eb7-bcb6-4d0f-981b-e3144ce2db1d.jpg>
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Arturgouveia1970/Personal-portofolio/pull/3#pullrequestreview-913506191>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWSD5UUUVDEVGMOCJ3GZTS3VANZF5ANCNFSM5Q4647EQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>