Repeat week
Arturgouveia1970/Personal-portofolio pull request #5
Opened 2022-03-23 14:40 UTC by Arturgouveia1970

in this pull request, work was made on the margins of the document.
general adjustments to the styling of the page.

2022-03-23 15:16 UTC, gemmen29 requested changes
Hi @Arturgouveia1970, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

## Required Changes ♻️
_Check the comments under the review._

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Optional suggestions
- [ ] [OPTIONAL] Kindly give the branch a meaningful name, not `repeat-week` like the name of the project `mobile-version`.
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-23 19:22 UTC, Arturgouveia1970 commented on index.html
> +    </section>
@gemmen29 , please I need help in how to remove this white space. I have tried @media and it does not change. there isn't one element that exceeds 375px of width. any suggestions?

2022-03-23 20:24 UTC, gemmen29 commented on index.html
> +    </section>
Yes, most of the problems come from this part
![image](https://user-images.githubusercontent.com/24703171/159789047-dc201418-aa6d-415a-bbb7-454f35ca7128.png)
try to change `margins` with `paddings` and get rid of fixed `widths` in that section

2022-03-23 22:27 UTC, Arturgouveia1970 commented on index.html
> +        <h2 id="skills"><img class="rect3" id="skill" src="images/Rectangle57.png" alt="Rectangle">Skills</h2>
linters tells me that I can't have ul as a child of ul. don't understand...

2022-03-23 22:35 UTC, sja-thedude reviewed
## Invalid Code Review Request ❌

Hi @Arturgouveia1970, This is @sja-thedude your code reviewer.

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, that doesn't pass all linters.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-03-24 15:04 UTC, CollinsTatang approved these changes
Hi @Arturgouveia1970 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![image](https://user-images.githubusercontent.com/55596970/158098566-50966056-ce3d-4c4b-aac3-cce7a7d107fb.png)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-24 15:19 UTC, merged